# Generated by Django 4.1.2 on 2022-10-24 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newmovies", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Movies", new_name="Movie",),
    ]
