# Generated by Django 4.1.2 on 2022-10-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newmovies", "0002_rename_movies_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="movie_image",
            field=models.ImageField(default="-", upload_to="static/images/movies"),
            preserve_default=False,
        ),
    ]
