# Generated by Django 4.1.2 on 2022-10-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newmovies", "0003_movie_movie_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tableform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_name", models.CharField(max_length=255)),
                ("director", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
            ],
        ),
    ]
