# Generated by Django 4.1.2 on 2022-10-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newmovies", "0004_tableform"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_img", models.ImageField(upload_to="static/images/actors")),
                ("actor_name", models.CharField(max_length=255)),
                ("actor_desc", models.TextField()),
            ],
        ),
    ]
